# podman build --rm -f Dockerfile.ocp -t quay.io/redhat_naps_da/hapi-fhir-jpaserver-starter-ocp:v5.3.0 .
# podman push quay.io/redhat_naps_da/hapi-fhir-jpaserver-starter-ocp:v5.3.0

FROM registry.redhat.io/jboss-webserver-5/webserver54-openjdk11-tomcat9-openshift-rhel8:1.0-12

USER root

RUN mkdir -p /data/hapi/lucenefiles && chmod 775 /data/hapi/lucenefiles

COPY ./target/ROOT.war /opt/jws-5.4/tomcat/webapps/
